name: Test_Unitaires_JS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install npm
        run: npm install -g npm@10.9.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
